source 'https://rubygems.org'
gem 'rails', '~> 8.1'
gem 'pg'
gem 'puma'
gem 'sidekiq'
gem 'aws-sdk-s3'
gem 'rspec-rails'
gem 'tzinfo-data'
gem 'redis'
gem 'httparty'
gem 'cloudinary'
gem 'rack-attack'
gem 'sqlite3'
gem 'webmock'
gem 'factory_bot_rails'